### PR TITLE
made decimal division fully dynamic

### PR DESCRIPTION
**Pull request by 0xModene**

### CODE REVIEW

**Comment by 0xModene** [comment]
@ckoopmann mind reviewing this and checking my math where needed?

**Comment by ckoopmann** [comment]
In the deploy preview the Liquidity numbers are now always 0 for any token and the other ones have lost the decimal precision (are always rounded to the nearest integer).

image

**Comment by 0xModene** [comment]
Screen Shot 2021-10-30 at 2 39 50 PM

perhaps this is an issue with threading? Is there a more reliable way we can structure it?

**Comment by ckoopmann** [comment]
> Screen Shot 2021-10-30 at 2 39 50 PM
> 
> perhaps this is an issue with threading? Is there a more reliable way we can structure it?

What exact issue are you refering to ? The 0 Max Trade size for COMP / Balancer ?

**Pull request closed without merging**
