### PR TITLE
Liquidity Analyzer: Add UniswapV3 1%, 0.05%, and 0.01% fee tiers

### PR DESCRIPTION
**Pull request by agentMAK**

### CODE REVIEW

**Comment by 0xModene** [comment]
What is this for?

**Comment by gmridul** [comment]
Hey @agentMAK , can you update this PR with an appropriate title, description and the related ticket on notion?

**Comment by agentMAK** [comment]
Edward has notifed me that you'd handle the deployment of npm for the folked set-protocol (index-rebalances-ultis). Has this need done yet? If so, this can be implemented to liquidity analyser and story will be fully completed.

**Comment by agentMAK** [comment]
Hi Mod, index-rebalance-utils pull request approved however not merged. 
https://github.com/SetProtocol/index-rebalance-utils/pull/13

**Pull request closed without merging**
